import Head from 'next/head'
import React from 'react'
import Navbar from './Navbar'

const Layout = ({title, children}) => {
  return (
    <div>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/pokeball.png" />
        </Head>
        <Navbar />
        <div className='sm:p-5 bg-gray-300 '>
            {children}
        </div>
    </div>
  )
}

export default Layout